using System.IO;

namespace gmtk2024.Editor.CodeGen;

public static class Constants
{
    public const string RootNamespace = "gmtk2024";
    public const string AssetsFolder = "Assets";
    public const string GeneratedFolder = "Generated";

    public const string OutputFileFormat = "{0}.g.cs";
    public const string AutoGenHeaderFormat =
        "//------------------------------------------------------------------------------\n"
        + "// <auto-generated>\n"
        + "//     This code was generated by a tool.\n"
        + "//     Generator: {0} \n"
        + "//     Target: {1}\n"
        + "//     Assembly: {2}\n"
        + "//\n"
        + "//     Changes to this file may cause incorrect behavior and will be lost if\n"
        + "//     the code is regenerated. To update the generation of this file, modify and re-run UnityCodeGen.\n"
        + "// </auto-generated>\n"
        + "//------------------------------------------------------------------------------\n";

    public static string GetAssemblyFileName(Type type)
    {
        var assembly = type.Assembly;
        var assemblyLocation = assembly.Location;
        return Path.GetFileName(assemblyLocation);
    }
}
