global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Threading.Tasks;
global using Cysharp.Threading.Tasks;
global using DG.Tweening;
global using Freya;
global using JacksonDunstan.NativeCollections;
global using JetBrains.Annotations;
global using pyr.Core;
global using pyr.Core.Collections;
global using pyr.Core.Singleton;
global using pyr.Core.Time;
global using static pyr.Shared.Common.Assertions;
global using pyr.Shared.Extensions;
global using pyr.Shared.Types;
global using pyr.Union;
global using static pyr.Union.Global;
global using pyr.Union.Monads;
global using SaintsField;
global using SaintsField.Playa;
global using Unity.Mathematics;
global using UnityEngine;
global using static UnityEngine.Debug;
global using f32 = System.Single;
global using f64 = System.Double;
global using Gizmos = UGizmo.UGizmos;
global using i16 = System.Int16;
global using i32 = System.Int32;
global using i64 = System.Int64;
global using i8 = System.SByte;
global using Math = Freya.Mathfs;
global using Random = Freya.Random;
global using Timer = pyr.Core.Time.Timer;
global using u16 = System.UInt16;
global using u32 = System.UInt32;
global using u64 = System.UInt64;
global using u8 = System.Byte;
